# Generated by Django 6.0.2 on 2026-03-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.TextField(max_length=150)),
                ('password', models.CharField(max_length=15)),
                ('checkbox', models.BooleanField(default=False)),
                ('photo', models.FileField(default=None, null=True, upload_to='')),
            ],
        ),
    ]
